
name: CI/CD Pipeline for Data prediction

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  data_prediction:
    runs-on: ubuntu-latest
    
    steps:
      # Krok 1: Checkout repozytorium
      - name: Checkout repository
        uses: actions/checkout@v2

      # Krok 2: Zainstaluj Python i zależności
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Krok 3: Uruchom skrypt
      - name: Run data prediction
        run: python main.py

      # Krok 4: Wyświetl wyniki
      - name: Display training result
        run: cat results.txt