
name: Build and Push Docker Image

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout repozytorium
      - name: Checkout repository
        uses: actions/checkout@v2

      # Zainstaluj Python i zależności
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Zaloguj do Dockera
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Zbuduj obraz Dockera
      - name: Build Docker image
        run: docker build -t jchainska/flask_score_predict:latest .

      # Wypchnij obraz na Docker Hub
      - name: Push Docker image
        run: docker push jchainska/flask_score_predict:latest
